name: Build Dylib
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: theos/setup-theos-action@v1

      - name: Build Package
        run: |
          # Guna SDK sedia ada atau skip signing
          make package FINALPACKAGE=1
        env:
          THEOS: ${{ github.workspace }}/theos
          CODESIGN_IPA: 0

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzuriteKey-Dylib
          path: "**/AzuriteKey.dylib"
