name: Build Dylib
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos & SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl perl git clang libicu-dev
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          mkdir -p $GITHUB_WORKSPACE/theos/sdks
          tar -xf iPhoneOS14.5.sdk.tar.xz -C $GITHUB_WORKSPACE/theos/sdks
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Build Package
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzuriteKey-Dylib
          path: obj/*.dylib
