name: Build Dylib
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: theos/setup-theos-action@v1

      - name: Download iOS SDK
        run: |
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          tar -xf iPhoneOS14.5.sdk.tar.xz -C $THEOS/sdks
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Build Package
        run: |
          make package FINALPACKAGE=1
